### Login Route
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "123456789",
    "remember": "false"
}

### Refresh-token Route
POST http://localhost:4000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJFbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE2MDQ0MjkwNTIsImV4cCI6MTYzNTk4NjY1Mn0.gigNMIN314ntuPGU1CNCCedP8JYdl4BQizs0DeBhP28"
}


### Contacts Route
GET http://localhost:4000/api/contacts
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsInVzZXJFbWFpbCI6InRlc3RAdGVzdC5jb20iLCJ1c2VyTmFtZSI6InRlc3QiLCJpYXQiOjE2MDQ0MjkwNTIsImV4cCI6MTYwNDQyOTA3Mn0.1cc6f99La8LBepcHHmU5cqZb9kc10LaueFLed3bIBRM
